Backend do inVicto
alexleandr/invicto-app-backend pull request #1
Opened 2023-05-06 17:04 UTC by alexleandr

Nessa etapa desenvolvi o backend do inVicto utilizando Express + MongoDB (mongoose), hash de senhas utilizando bcrypt e esquema de autenticação jsonwebtoken. Foram comentados todos models, controllers e services para melhor entendimento do código.

2023-05-09 04:20 UTC, CaioVinicius7 requested changes

2023-05-09 04:20 UTC, CaioVinicius7 commented on package.json
> +    "dev": "nodemon src index.js"
Se você estiver utilizando a versão 18 pra cima do node não é necessário essa lib, em vez disso você pode utilizar o seguinte script `node --watch index.js`

2023-05-09 04:20 UTC, CaioVinicius7 commented on src/config/database.js
> +const database = process.env.MONGODB_URI
Eu mudaria o nome dessa para algo como `mongUri` e faria o seguinte:

`const mongoUri = process.env.MONGODB_URI ?? "";`

O código acima atribui uma string vazia para a const `mongoUri` caso o `process.env.MONGODB_URI` for `nulo `ou `undefine`.

2023-05-09 04:20 UTC, CaioVinicius7 commented on src/index.js
> +const port = 1406
Você pode salvar essa porta em uma variável de ambiente.

2023-05-09 04:20 UTC, CaioVinicius7 commented on src/index.js
> +const authController = require('./controllers/auth')
não coloquei em cada arquivo isso, porém seria melhor separar um arquivo para rotas e outro para controller, do jeito que está o controller está acoplado a rota.

2023-05-09 04:20 UTC, CaioVinicius7 commented on src/middlewares/verifyToken.js
> +  const token = req.headers['x-access-token']
Como é um token jwt você pode passar ele em um header chamado `Authorization`, esse é o padrão utilizado.

Pelo insominia/postman seria passado algo como o exemplo abaixo:

`Authorization: Bearer ${token}`

2023-05-09 04:20 UTC, CaioVinicius7 commented on src/models/feedback.js
> +    via: {
deixaria o nome para inglês, para manter o padrão.

2023-05-09 04:20 UTC, CaioVinicius7 commented on src/models/feedback.js
> +    user_feedback: {
Acho que aqui em vez de `user_feedback` você pode colocar algo como `message`.

Acho que deve ficar melhor organizado, pois cada Feedback terá o autor, por onde ele deu o feedback e a mensagem de feedback.

2023-05-11 20:15 UTC, alexleandr commented on src/models/feedback.js
> +    via: {
Está em inglês, é a mesma palavra nas duas línguas

2023-05-15 21:33 UTC, CaioVinicius7 approved these changes

2023-05-15 22:27 UTC, merged